### ISSUE TITLE
Use this plugin not only for legacy code

### ISSUE THREAD

**Issue by ramabouda** [bholloway/omit-tilde-webpack-plugin#3]
The tilde prefixing looks a lot like a hack, since it's not allowed by the SASS syntax. What do you think of using this module to avoid having to put the `~` and keep correct SASS files ?

I'm asking the question since your README tells it should not be used elsewhere.
To me, both are hackish, but your plugin does change the source files.

**Comment by bholloway** [comment]
@raphael-boucher my feelings are split on the subject.

I do not want to guide people away from the webpack conventions.  However I appreciate that many/most people who find this plugin will want to omit the tilde all the time.

So while I recommend you follow webpack conventions I default the `deprecate` flag to `false`.

Fundamentally SASS does not support the module concept. Without the tilde the SASS syntax is ambiguous. If you use this plugin permanently you accept the following:
- The overhead of the additional resolve step (it includes at least one [filesystem operation](https://github.com/bholloway/omit-tilde-webpack-plugin/blob/master/index.js#L98))
- The risk of name conflicts between files and modules (resolved in favour of files)

I think this is reasonable. And if you do find a bug I'm usually pretty prompt at attending to it.

It depends on what additional considerations you may have...

At my own work we have a large number of developers. We try to follow the Webpack conventions because deviation can cause its own confusion. We also like to minimise our dependence on loaders/plugins where we can. For that reason we run in `deprecate` mode and migrate our code. With the long term aim to remove the plugin.

**Comment by ramabouda** [comment]
Thanks for the very detailed explanation, all seems very reasonable!
